spring.datasource.url=jdbc:postgresql://10.0.0.100:5432/caliper
spring.datasource.username=root
spring.datasource.password=Admin@12345
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
file.upload.dir=/data/file-upload

gmb.data.dir=//app//GMB-Connect//client_secrets.json
gmb.cred.dir=//app//GMB-Connect

gmb.oauth.redirect-uri=https://backend-uat.thecaliper.ai/gmb-oauth/callback
log.path = //app//logs//

facebook.oauth.redirect-uri=https://backend-uat.thecaliper.ai/facebook-oauth/callback

# Email credentials for UAT environment
spring.mail.username=AKIASMHHLCQYEVMXOVSA
spring.mail.password=BDaB0Md5AM6MmZUYB4kcqjyqbEw16nOKlCIoNgKDKnfP

# Frontend URL for password reset link (UAT - must use HTTPS)
app.password-reset.url=https://thecaliper.ai/reset

# Frontend URL for email verification link (UAT - must use HTTPS)
app.email-verification.url=https://thecaliper.ai/verify-email

#This used for after GMB or META OAuth connection success 
gmb.connection.success.url = https://thecaliper.ai/account-access
facebook.connection.success.url = https://thecaliper.ai/account-access