package com.caliper.campaign.google.entity;

import java.util.Date;


import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Builder
@Data
@AllArgsConstructor
@NoArgsConstructor
public class ArtAdwordsData {

	public static final String SQL_TABLE = "ADWORDS";

	public static final String SQL_COLUMN_CREATED_AT = "CreatedAt";
	public static final String SQL_COLUMN_REPORT_TYPE = "ReportType";
	public static final String SQL_COLUMN_AD_GROUP_NAME = "AdGroupName";
	public static final String SQL_COLUMN_AD_GROUP_ID = "AdGroupId";
	public static final String SQL_COLUMN_AD_GROUP_STATUS = "AdGroupStatus";
	public static final String SQL_COLUMN_CAMPAIGN_ID = "CampaignId";
	public static final String SQL_COLUMN_CAMPAIGN_NAME = "CampaignName";
	public static final String SQL_COLUMN_DATE = "Date";
	public static final String SQL_COLUMN_CLICKS = "Clicks";
	public static final String SQL_COLUMN_IMPRESSIONS = "Impressions"; 
	public static final String SQL_COLUMN_CTR = "CTR";
	public static final String SQL_COLUMN_COST = "Cost";
	public static final String SQL_COLUMN_CONVERSIONS = "Conversions";
	public static final String SQL_COLUMN_VIEW_THRU_CONVERSIONS = "ViewThruConversions";
	public static final String SQL_COLUMN_COST_PER_CONVERSION = "CostPerConversion";
	public static final String SQL_COLUMN_CONVERSION_RATE = "ConversionRate";
	public static final String SQL_COLUMN_ACCOUNT_CURRENCY_CODE = "AccountCurrencyCode";
	public static final String SQL_COLUMN_BIDDING_STRATEGY_NAME = "BiddingStrategyName";
	public static final String SQL_COLUMN_BIDDING_STRATEGY_TYPE = "BiddingStrategyType";
	public static final String SQL_COLUMN_ADVERTISING_CHANNEL_TYPE = "AdvertisingChannelType";
	public static final String SQL_COLUMN_ADVERTISING_CHANNEL_SUB_TYPE = "AdvertisingChannelSubType";
	public static final String SQL_COLUMN_CAMPAIGN_STATUS = "CampaignStatus";
	public static final String SQL_COLUMN_AMOUNT = "Amount";
	public static final String SQL_COLUMN_SEARCH_IMPRESSION_SHARE = "SearchImpressionShare";
	public static final String SQL_COLUMN_AVERAGE_CPM = "AverageCpm";
	public static final String SQL_COLUMN_VIDEO_VIEWS = "VideoViews";
	public static final String SQL_COLUMN_VIDEO_VIEW_RATE = "VideoViewRate";
	public static final String SQL_COLUMN_VIDEO_QUARTILE_25_RATE = "VideoQuartile25Rate";
	public static final String SQL_COLUMN_VIDEO_QUARTILE_50_RATE = "VideoQuartile50Rate";
	public static final String SQL_COLUMN_VIDEO_QUARTILE_75_RATE = "VideoQuartile75Rate";
	public static final String SQL_COLUMN_VIDEO_QUARTILE_100_RATE = "VideoQuartile100Rate";
	public static final String SQL_COLUMN_INTERACTIONS = "Interactions";
	public static final String SQL_COLUMN_INTERACTION_RATE = "InteractionRate";
	public static final String SQL_COLUMN_CITY = "City";
	public static final String SQL_COLUMN_REGION = "Region";
	public static final String SQL_COLUMN_COUNTRY = "Country";
	public static final String SQL_COLUMN_IA_CAMPAIGN_ID = "IACampaignId";
	public static final String SQL_COLUMN_UNIQUE_ID = "UniqueId";
	public static final String SQL_COLUMN_ENGAGEMENT_RATE = "EngagementRate";
	public static final String SQL_COLUMN_AD_GROUP_TYPE = "AdGroupType";
	public static final String SQL_COLUMN_AVERAGE_CPC = "AverageCpc";
	public static final String SQL_COLUMN_PHONE_CALLS = "PhoneCalls";
	public static final String SQL_COLUMN_PHONE_IMPRESSION = "PhoneImpressions";
	public static final String SQL_COLUMN_CONVERSIONS_FROM_INTERACTIONS_RATE = "ConversionsFromInteractionsRate";
	public static final String SQL_COLUMN_SEARCH_RANK_LOST_IMPRESSION_SHARE = "SearchRankLostImpressionShare";
	public static final String SQL_COLUMN_CAMPAIGN_GROUP_NAME = "CampaignGroupName";
	public static final String SQL_COLUMN_ALL_CONVERSIONS_FROM_STORE_VISIT = "AllConversionsFromStoreVisit";
	public static final String SQL_COLUMN_SEARCH_BUDGET_LOST_IMPRESSION_SHARE = "SearchBudgetLostImpressionShare";
	public static final String SQL_COLUMN_ALL_CONVERSIONS = "AllConversions";
	public static final String SQL_COLUMN_ENGAGEMENTS = "Engagements";
	public static final String SQL_COLUMN_SEARCH_ABS_TOP_IS = "SearchAbsTopIS";
	public static final String SQL_COLUMN_SEARCH_EXACT_MATCH_IS = "SearchExactMatchIS";
	public static final String SQL_COLUMN_SEARCH_BUDGET_LOST_ABSOLUTE_TOP_IMPRESSION_SHARE = "SearchBudgetLostAbsoluteTopImpressionShare";
	public static final String SQL_COLUMN_SEARCH_RANK_LOST_ABSOLUTE_TOP_IMPRESSION_SHARE = "SearchRankLostAbsoluteTopImpressionShare";
	public static final String SQL_COLUMN_CAMPAIGN_BUGET_AMOUNT_MICROS = "CampaignBudgetAmountMicros";
	public static final String SQL_COLUMN_SEARCH_BUDGET_LOST_TOP_IMPRESSION_SHARE = "SearchBudgetLostTopImpressionShare";
	public static final String SQL_COLUMN_SEARCH_RANK_LOST_TOP_IMPRESSION_SHARE = "SearchRankLostTopImpressionShare";
	public static final String SQL_COLUMN_VIEW_THROUGH_CONVERSIONS = "ViewThroughConversions";
	public static final String SQL_COLUMN_CROSS_DEVICE_CONVERSIONS = "CrossDeviceConversions";
	public static final String SQL_COLUMN_TARGET_CPA_MICROS = "TargetCpaMicros";
	public static final String SQL_COLUMN_TARGET_IMPRESSION_SHARE_CPC_BID_CEILING_MICROS = "TargetImpressionShareCpcBidCeilingMicros";
	public static final String SQL_COLUMN_TARGET_ROAS = "TargetRoas";
	public static final String SQL_COLUMN_PHONE_THROUGH_RATE = "PhoneThroughRate";
	public static final String SQL_COLUMN_GMAIL_SECONDARY_CLICKS = "GmailSecondaryClicks";
	public static final String SQL_COLUMN_GMAIL_FORWARDS = "GmailForwards";
	public static final String SQL_COLUMN_SEARCH_CLICK_SHARE = "SearchClickShare";
	public static final String SQL_COLUMN_CONVERSION_VALUE = "ConversionsValue";
	public static final String SQL_COLUMN_PARTNER_ID = "PartnerId";
	public static final String SQL_COLUMN_PARTNER_NAME = "PartnerName";

	private Date createdAt;
	private String reportType;
	private String adGroupName;
	private String adGroupId;
	private String adGroupStatus;
	private String campaignId;
	private String campaignName;
	private Date date;
	private double clicks;
	private double impressions;
	private double ctr;
	private double cost;
	private double conversions;
	private double viewThruConversions;
	private double costPerConversion;
	private double conversionRate;
	private String accountCurrencyCode;
	private String biddingStrategyName;
	private String biddingStrategyType;
	private String advertisingChannelType;
	private String advertisingChannelSubType;
	private String campaignStatus;
	private double amount;
	private double searchImpressionShare;
	private double averageCpm;
	private double videoViews;
	private double videoViewRate;
	private double videoQuartile25Rate;
	private double videoQuartile50Rate;
	private double videoQuartile75Rate;
	private double videoQuartile100Rate;
	private double interactions;
	private double interactionRate;
	private String city;
	private String region;
	private String country;
	private double iACampaignId;
	private String uniqueId;
	private double engagementRate;
	private String adGroupType;
	private double averageCpc;
	private double phoneCalls;
	private double phoneImpressions;
	private double conversionsFromInteractionsRate;
	private double searchRankLostImpressionShare;
	private String campaignGroupName;
	private double allConversionsFromStoreVisit;
	private double searchBudgetLostImpressionShare;
	private double allConversions;
	private double engagements;
	private double searchAbsTopIS;
	private double searchExactMatchIS;
	private double searchBudgetLostAbsoluteTopImpressionShare;
	private double searchRankLostAbsoluteTopImpressionShare;
	private double campaignBudgetAmountMicros;
	private double searchBudgetLostTopImpressionShare;
	private double searchRankLostTopImpressionShare;
	private double viewThroughConversions;
	private double crossDeviceConversions;
	private double targetCpaMicros;
	private double targetImpressionShareCpcBidCeilingMicros;
	private double targetRoas;
	private double phoneThroughRate;
	private double gmailSecondaryClicks;
	private double gmailForwards;
	private double searchClickShare;
	private double conversionsValue;
	private String partnerId;
	private String partnerName;

}
